#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_PATH="$ROOT_DIR/AppStoreConnectMCP.xcworkspace"
SCHEME="AppStoreConnectMCP"
CONFIGURATION="${MCP_BUILD_CONFIGURATION:-Release}"
BUILD_ROOT="$ROOT_DIR/.build/npm-universal"
DIST_DIR="$ROOT_DIR/dist"
OUTPUT_BINARY="$DIST_DIR/AppStoreConnectMCP"

if [[ ! -d "$WORKSPACE_PATH" ]]; then
  echo "Workspace file not found at $WORKSPACE_PATH. It will be generated by Tuist." >&2
fi

if ! command -v tuist >/dev/null 2>&1; then
  echo "Tuist is required but was not found in PATH." >&2
  exit 1
fi

echo "Resolving Tuist dependencies and regenerating project..."
tuist install >/dev/null
tuist generate >/dev/null

rm -rf "$BUILD_ROOT"
mkdir -p "$DIST_DIR"

build_for_arch() {
  local arch="$1"
  local derived_data="$BUILD_ROOT/$arch"

  echo "Building $SCHEME ($CONFIGURATION) for $arch..."
  tuist xcodebuild \
    -workspace "$WORKSPACE_PATH" \
    -scheme "$SCHEME" \
    -configuration "$CONFIGURATION" \
    -destination "platform=macOS,arch=$arch" \
    -derivedDataPath "$derived_data" \
    OTHER_LDFLAGS="\$(inherited) -lswiftSynchronization" \
    build
}

build_for_arch "arm64"
ARM64_BINARY="$BUILD_ROOT/arm64/Build/Products/$CONFIGURATION/AppStoreConnectMCP"

if [[ ! -f "$ARM64_BINARY" ]]; then
  echo "Failed to locate arm64 build product at $ARM64_BINARY." >&2
  exit 1
fi

ARM64_ARCHS="$(lipo -archs "$ARM64_BINARY" 2>/dev/null || true)"
if [[ "$ARM64_ARCHS" == *"arm64"* && "$ARM64_ARCHS" == *"x86_64"* ]]; then
  cp "$ARM64_BINARY" "$OUTPUT_BINARY"
  chmod 755 "$OUTPUT_BINARY"
  echo "Build product already universal: $ARM64_ARCHS"
  echo "Universal binary written to $OUTPUT_BINARY"
  exit 0
fi

build_for_arch "x86_64"
X64_BINARY="$BUILD_ROOT/x86_64/Build/Products/$CONFIGURATION/AppStoreConnectMCP"
if [[ ! -f "$X64_BINARY" ]]; then
  echo "Failed to locate x86_64 build product at $X64_BINARY." >&2
  exit 1
fi

echo "Creating universal binary from arm64 + x86_64 artifacts..."
lipo -create "$ARM64_BINARY" "$X64_BINARY" -output "$OUTPUT_BINARY"
chmod 755 "$OUTPUT_BINARY"

echo "Universal binary written to $OUTPUT_BINARY"
echo "Architectures: $(lipo -archs "$OUTPUT_BINARY")"
